"""Shared constants for the Airflow API Server charm."""

SERVICE_NAME = "airflow"
CONTAINER_NAME = "airflow-dag-processor"
AIRFLOW_COMPONENT = "dag-processor"
AIRFLOW_COORDINATOR_RELATION_NAME = "airflow-coordinator"
AIRFLOW_HOME = "/opt/airflow"
AIRFLOW_CONFIG_PATH = f"{AIRFLOW_HOME}/airflow.cfg"
WORKLOAD_USER = "ubuntu"
WORKLOAD_GROUP = "ubuntu"
