# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
min_version = 4.0
env_list = lock, lint, format, integration
no_package = true

[testenv]
skip_install = true
passenv = *
setenv =
    PYTHONPATH = {toxinidir}
allowlist_externals =
    uv
    bash
    curl
    charmcraft
    juju

[testenv:lock]
description = generate/refresh uv.lock
commands =
    uv lock

[testenv:integration]
description = run integration tests (using uv.lock)
setenv =
    PYTHONPATH = {toxinidir}
    UV_PROJECT_ENVIRONMENT = {envdir}
    UV_LINK_MODE = copy
commands =
    uv sync --frozen --group integration
    uv run --active python -m pytest -vv -s {posargs:tests/integration}

[testenv:lint]
description = run ruff lint
setenv =
    PYTHONPATH = {toxinidir}
    UV_PROJECT_ENVIRONMENT = {envdir}
    UV_LINK_MODE = copy
commands =
    uv sync --frozen --group lint
    uv run --active ruff check tests/integration

[testenv:format]
description = run ruff format check
setenv =
    PYTHONPATH = {toxinidir}
    UV_PROJECT_ENVIRONMENT = {envdir}
    UV_LINK_MODE = copy
commands =
    uv sync --frozen --group format
    uv run --active ruff format  tests/integration

[tool.pytest.ini_options]
addopts = "-p no:pytest_operator"
