set export := true # Just variables are exported into environment variables

[private]
default:
    just --list

[private]
initialize:
    #!/usr/bin/bash
    if [ ! -d ".terraform" ]; then
        terraform init
    fi

[private]
destroy-model:
    #!/usr/bin/bash
    if [ "${CI:-}" = "true" ]; then
        juju destroy-model --no-prompt --destroy-storage --no-wait terraform || true
        sleep 60
    else
        juju destroy-model --no-prompt --destroy-storage terraform || true
    fi

[private]
add-model: (destroy-model)
    juju add-model terraform

[private]
validate_test_tfvars variables_file:
    #!/usr/bin/bash
    MODEL_UUID=$(juju show-model terraform --format=json | jq -r '.terraform["model-uuid"]')
    if ! juju show-model "${MODEL_UUID}" >/dev/null 2>&1; then
        exit 1
    fi
    echo "model_uuid = \"${MODEL_UUID}\"" >> "${variables_file}"

# Run terraform format
fmt: (initialize)
    terraform fmt

# Run terraform validate
validate: (initialize)
    terraform validate

# Run tflint
lint:
    tflint

# Apply the terraform plan with the provided variables file
apply variables_file: (initialize)
    terraform apply -auto-approve -var-file="${variables_file}"

# Destroy the terraform plan with the provided variables file
destroy variables_file:
    #!/usr/bin/bash
    terraform destroy -auto-approve -var-file="${variables_file}"

    just destroy-model
    sed '/model_uuid/d' -i "${variables_file}"

test:
    #!/usr/bin/bash
    set -euxo pipefail

    trap 'just destroy "./test/test.tfvars"' EXIT

    just add-model

    just validate_test_tfvars "./test/test.tfvars"

    just apply "./test/test.tfvars"

    juju wait-for model terraform --query="forEach(units, unit => (unit.workload-status == 'blocked' && unit.workload-message == 'Missing airflow-coordinator relation'))"
