name: Publish changed charms

on:
  push:
    branches:
      - "track/*"

jobs:
  get-modified-charms:
    name: Detect changed charms
    uses: canonical/workflows-team/.github/workflows/get_modified_directories_by_marker.yaml@main
    with:
      base-ref: ${{ github.event.before }}
      marker: charmcraft.yaml
      search-root: charms
    secrets: inherit

  publish:
    name: Publish changed charms
    needs: get-modified-charms
    if: ${{ needs.get-modified-charms.outputs.paths != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        charm_path: ${{ fromJSON(needs.get-modified-charms.outputs.paths) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute tag prefix
        id: meta
        shell: bash
        run: |
          echo "tag_prefix=$(basename '${{ matrix.charm_path }}')" >> "$GITHUB_OUTPUT"

      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@2.6.2
        with:
          credentials: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          charm-path: ${{ matrix.charm_path }}
          channel: 3.1/edge
          tag-prefix: ${{ steps.meta.outputs.tag_prefix }}
          charmcraft-channel: 3.x/stable
