name: Spread Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spread:
    name: Spread Tests (LXD)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1

      - name: Install Spread
        run: |
          sudo snap install spread

      - name: Run Spread Tests
        run: |
          spread -v lxd:ubuntu-24.04-64