name: CI

on:
  pull_request:
  workflow_call:

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory:
          - charms/airflow-api-server
          - charms/airflow-scheduler
          - charms/airflow-dag-processor
          - charms/airflow-triggerer
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Run Linter
        working-directory: ${{ matrix.directory }}
        run: uv tool run tox -e lint

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory:
          - charms/airflow-api-server
          - charms/airflow-scheduler
          - charms/airflow-dag-processor
          - charms/airflow-triggerer
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Run Tests
        working-directory: ${{ matrix.directory }}
        run: uv tool run tox -e unit

  discover-integration-tasks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.out.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate integration test matrix
        id: out
        shell: bash
        run: |
          FILES=$(ls -1 tests/integration/test_*.py 2>/dev/null || true)

          if [ -z "$FILES" ]; then
            echo 'matrix={"include":[]}' >> "$GITHUB_OUTPUT"
            exit 0
          fi

          MATRIX=$(printf '%s\n' $FILES | jq -R . | jq -s '{include: map({test_file: .})}')
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"

  integration-tests:
    needs: [lint, unit-tests, discover-integration-tasks]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.discover-integration-tasks.outputs.matrix) }}

    if: ${{ needs.discover-integration-tasks.outputs.matrix != '{"include":[]}' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install

      - name: Run integration test file
        run: uv tool run tox -e integration -- ${{ matrix.test_file }}
