name: tests

on:
  pull_request:
  workflow_call:
    inputs:
      directories:
        required: false
        type: string
        default: '["charms/api-server","charms/scheduler","charms/dag-processor","charms/triggerer"]'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJSON(inputs.directories) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo snap install astral-uv --classic
          uv tool install tox

      - name: Run Linter
        working-directory: ${{ matrix.directory }}
        run: uv tool run tox -e lint

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJSON(inputs.directories) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo snap install astral-uv --classic
          uv tool install tox

      - name: Run Tests
        working-directory: ${{ matrix.directory }}
        run: uv tool run tox -e unit

  discover-integration-tasks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.out.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Generate integration test matrix
        id: out
        shell: bash
        run: |
          FILES=$(ls -1 tests/integration/test_*.py 2>/dev/null || true)

          if [ -z "$FILES" ]; then
            echo 'matrix={"include":[]}' >> "$GITHUB_OUTPUT"
            exit 0
          fi
          MATRIX=$(printf '%s\n' $FILES | jq -R . | jq -s '{include: map({test_file: .})}')
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"

  integration-tests:
    needs: [lint, unit-tests, discover-integration-tasks]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.discover-integration-tasks.outputs.matrix) }}
    if: ${{ needs.discover-integration-tasks.outputs.matrix != '{"include":[]}' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies (concierge)
        shell: bash
        run: |
          set -euo pipefail

          sudo apt-get update
          sudo apt-get purge -y $(dpkg -l | grep -i docker | awk '{print $2}') || true
          sudo apt-get purge -y containerd.io || true
          sudo rm -rf /run/containerd || true

          sudo snap install concierge --classic
          sudo snap install just --classic

          sudo -E concierge prepare -p k8s --extra-snaps=astral-uv

          mkdir -p ~/.kube
          sudo k8s kubectl config view --raw > ~/.kube/config

          uv tool install tox

      - name: Run integration test file
        run: uv tool run tox -e integration -- ${{ matrix.test_file }}
